import { Food } from './app/shared/models/Food';

export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'Pizza',
    price: 10,
    tag: ['fastfood', 'food', 'snack'],
    favourite: false,
    stars: 4.5,
    imageUrl:
      '../assets/240376-homemade-pepperoni-pizza-Beauty-3x4-1-6ae54059c23348b3b9a703b6a3067a44.jpg',
    origins: ['italy'],
    cookTime: '10.20',
  },
  {
    id: '2',
    name: 'Cheese',
    price: 30,
    tag: ['fastcheese', 'foodcheese', 'snackcheese'],
    favourite: false,
    stars: 3.5,
    imageUrl:
      '../assets/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2015__10__20151017-pies-vicky-wasik-2-6f491edb6065485a86d6af639a592298.jpg',
    origins: ['sweden'],
    cookTime: '20-30',
  },
  {
    id: '3',
    name: 'Beer',
    price: 90,
    tag: ['fastfoodbeer', 'foodbeer', 'snackbeer'],
    favourite: true,
    stars: 5,
    imageUrl: '../assets/gettyimages-1386915196.jpg',
    origins: ['america'],
    cookTime: '5-7',
  },
  {
    id: '4',
    name: 'Coconut',
    price: 60,
    tag: ['fastfoodcoconut', 'foodcoconut', 'snackcoconut'],
    favourite: false,
    stars: 2.5,
    imageUrl: '../assets/cool-young.webp',
    origins: ['india'],
    cookTime: '17-90',
  },
  {
    id: '5',
    name: 'Chicken',
    price: 100,
    tag: ['fastfoodchicken', 'foodchicken', 'snackchicken'],
    favourite: true,
    stars: 4.5,
    imageUrl: '../assets/kfc-chicken-1.jpeg',
    origins: ['england'],
    cookTime: '10.20',
  },
  {
    id: '6',
    name: 'Pizza',
    price: 10,
    tag: ['fastfood', 'food', 'snack'],
    favourite: false,
    stars: 4.5,
    imageUrl:
      '../assets/240376-homemade-pepperoni-pizza-Beauty-3x4-1-6ae54059c23348b3b9a703b6a3067a44.jpg',
    origins: ['italy'],
    cookTime: '10.20',
  },
  {
    id: '7',
    name: 'Cheese',
    price: 30,
    tag: ['fastcheese', 'foodcheese', 'snackcheese'],
    favourite: false,
    stars: 3.5,
    imageUrl:
      '../assets/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2015__10__20151017-pies-vicky-wasik-2-6f491edb6065485a86d6af639a592298.jpg',
    origins: ['sweden'],
    cookTime: '20-30',
  },
  {
    id: '8',
    name: 'Beer',
    price: 90,
    tag: ['fastfoodbeer', 'foodbeer', 'snackbeer'],
    favourite: true,
    stars: 5,
    imageUrl: '../assets/gettyimages-1386915196.jpg',
    origins: ['america'],
    cookTime: '5-7',
  },
  {
    id: '9',
    name: 'Coconut',
    price: 60,
    tag: ['fastfoodcoconut', 'foodcoconut', 'snackcoconut'],
    favourite: false,
    stars: 2.5,
    imageUrl: '../assets/cool-young.webp',
    origins: ['india'],
    cookTime: '17-90',
  },
  {
    id: '10',
    name: 'Chicken',
    price: 100,
    tag: ['fastfoodchicken', 'foodchicken', 'snackchicken'],
    favourite: true,
    stars: 4.5,
    imageUrl: '../assets/kfc-chicken-1.jpeg',
    origins: ['england'],
    cookTime: '10.20',
  },
  {
    id: '11',
    name: 'Coconut',
    price: 60,
    tag: ['fastfoodcoconut', 'foodcoconut', 'snackcoconut'],
    favourite: false,
    stars: 2.5,
    imageUrl: '../assets/cool-young.webp',
    origins: ['india'],
    cookTime: '17-90',
  },
  {
    id: '12',
    name: 'Chicken',
    price: 100,
    tag: ['fastfoodchicken', 'foodchicken', 'snackchicken'],
    favourite: true,
    stars: 4.5,
    imageUrl: '../assets/kfc-chicken-1.jpeg',
    origins: ['england'],
    cookTime: '10.20',
  },
];
